### ISSUE TITLE
If control extends from class 

### ISSUE THREAD

**Issue by michogar** [IET-Xunta/XVM#1]
and not from Control, app load control without any problem. Do not launch any throw

**Comment by jorgelf** [comment]
I should do more tests to confirm all this, but I think that due to the way javascript works this is an unavoidable problem. But if you add a control from a code that doesn't include the methods listed in Control, it will either do nothing at all or directly crash, so I don't see a major problem here, no really weird behavior should happen. We could try to check the prototype from each object, even in a recursive way, but I think using javascript means we don't have strong typed objects, and we should write code in that way.

**Comment by michogar** [comment]
Ok, I think in Java but this is JavaScript, maybe not be interesting to waste time in enhancement this question. Close this Issue
