### ISSUE TITLE
Layer order TOC != Layer order map

### ISSUE THREAD

**Issue by nachouve** [IET-Xunta/XVM#9]
It seems that  parameter "layer_position : !!int 1" set  on config file "map.layers.yaml" is not the order used on the layer map. 

Anyway, layers are showed on the right order on the TOC.

**Comment by jorgelf** [comment]
Yes, you are right, orders are inconsistent. In fact, the TOC order is the wrong one, because that's not how the layers are stored inside the map. OpenLayers lets us set the index of the layers, but those indexes must make sense in the layers array (i.e. you can't specify an index of 50 if you don't have at least 51 layers). I'm going to order the layers by their layer_position before adding them to the map, and to generate the tree TOC in reverse order so it describes the actual layer configuration.
